# Generated by Django 5.2.6 on 2025-09-16 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.CharField(max_length=10)),
                ('initials', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_operation_center', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_off_duty_time', models.FloatField(default=0)),
                ('total_sleeper_berth_time', models.FloatField(default=0)),
                ('total_driving_time', models.FloatField(default=0)),
                ('total_on_duty_time', models.FloatField(default=0)),
                ('total_driving_miles', models.FloatField()),
                ('vehicle_number', models.CharField(default='P0000', max_length=50)),
                ('trailer_number', models.CharField(default='T00000', max_length=50)),
                ('shipper_name', models.CharField(blank=True, max_length=255)),
                ('shipper_commodity', models.IntegerField(blank=True)),
                ('load_number', models.IntegerField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver')),
            ],
            options={
                'ordering': ['date', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='DutyEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_event_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('truck_moved', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_time', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.driver')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('stop_type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('rest', 'Rest Stop'), ('pretrip', 'Pre-Trip Inspection'), ('posttrip', 'Post-Trip Inspection'), ('pickup', 'Pickup Location'), ('dropoff', 'Dropoff Location'), ('loading', 'Loading Freight'), ('offloading', 'Offloading Freight')], max_length=255)),
                ('arrival_time', models.DateField()),
                ('depature_time', models.DateField()),
                ('duration', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['arrival_time'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip'),
        ),
    ]
